version: '3.8'
services:
  postgresql:
    image: 'postgres'
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=concher_admin
      - POSTGRES_PASSWORD=concher1234
    # env_file:
    #   - ./docker.env
    ports:
      - 5432:5432
    # networks:
    #   - tmdb-net
  raven:
    image: 'postgres'
    volumes:
        - data:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=concher_admin
        - POSTGRES_PASSWORD=concher1234
    env_file:
        - ./docker.env
    ports:
        - 4545:3000
volumes:
  data: